name: orbitsounds
description: OrbitSounds mobile app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  heroicons: ^0.11.0
  http: ^1.2.2
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5
  geolocator: ^12.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.2.0
  audioplayers: ^6.1.0
  flutter_local_notifications: ^17.2.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_svg: ^2.0.9
  path_drawing: ^1.0.1
  feather_icons: ^1.2.0
  marquee: ^2.2.3
  intl: ^0.19.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  flutter_sound: ^9.4.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/medals/
    - .env
